# Secure deployment example for Daikin XML Listener
# This file requires a .env file with environment variables (see .env.example)
version: '3.8'

services:
  xml-listener:
    image: xml-stream-aggregator:latest
    container_name: xml-listener
    restart: unless-stopped
    
    # Network configuration
    networks:
      - internal
    ports:
      # Bind only to localhost - use a reverse proxy or firewall for external access
      - "127.0.0.1:8080:8080"
    
    # Resource limits (limits are supported, reservations require Swarm mode)
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    
    # Security options
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /app/data:mode=1777,size=100M
    
    # Environment variables from .env file
    environment:
      # Network settings
      BIND_HOST: ${BIND_HOST}
      PORT: ${PORT}
      
      # Security settings
      MAX_CONNECTIONS: ${MAX_CONNECTIONS}
      MAX_MESSAGE_SIZE: ${MAX_MESSAGE_SIZE}
      RATE_LIMIT_ENABLED: ${RATE_LIMIT_ENABLED}
      RATE_LIMIT_WINDOW: ${RATE_LIMIT_WINDOW}
      RATE_LIMIT_MAX_EVENTS: ${RATE_LIMIT_MAX_EVENTS}
      
      # S3 Configuration (use secrets in production)
      BUCKET_NAME: ${BUCKET_NAME}
      PREFIX: ${PREFIX}
      AWS_REGION: ${AWS_REGION}
      
      # File management
      ROTATION_INTERVAL: ${ROTATION_INTERVAL}
      MAX_FILE_SIZE: ${MAX_FILE_SIZE}
      OUTPUT_FORMAT: ${OUTPUT_FORMAT}
      USE_DATE_FOLDERS: ${USE_DATE_FOLDERS}
      PRETTY_PRINT_JSON: ${PRETTY_PRINT_JSON}
      
      # Paths (using tmpfs)
      CURRENT_FILE: ${CURRENT_FILE}
      TEMP_FILE: ${TEMP_FILE}
    
    # Use secrets for sensitive data (create these separately)
    secrets:
      - aws_access_key_id
      - aws_secret_access_key
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s = socket.socket(socket.AF_INET, socket.SOCK_STREAM); s.connect(('localhost', 8080)); s.close()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Networks
networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# Secrets (create these files with proper permissions for production)
secrets:
  aws_access_key_id:
    file: ./secrets/aws_access_key_id.txt
    external: true
  aws_secret_access_key:
    file: ./secrets/aws_secret_access_key.txt
    external: true